//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sign_Service_Label_Products.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_users
    {
        public int admin_user_id { get; set; }
        public string admin_username { get; set; }
        public string admin_password { get; set; }
        public string admin_salt { get; set; }
    }
}
