//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sign_Service_Label_Products.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class public_users
    {
        public int user_id { get; set; }
        public string contact_name { get; set; }
        public string email { get; set; }
        public string company_name { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string address_line_1 { get; set; }
        public string address_line_2 { get; set; }
        public string city { get; set; }
        public string state_province { get; set; }
        public string zip_postal { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
    }
}
